### ISSUE TITLE
Image attachments have wrong URL in admin dashboard

### ISSUE THREAD

**Issue by jhankin** [Raheem-ai/seed_web#47]
Did a little more digging and it looks like the image attachments are working correctly, but there's a little bug in the admin dashboard where the URL gets rendered improperly.  So for http://raheem.ai/admin/attachment/5, the admin page tries to show an image located at http://raheem.ai/admin/attachment/www.raheem.ai/media/W1siZiIsIm4xYWVwNHh1aXdlbHBycXNwd3hhLmpwZyJdXQ/17555505_10101361529505761_792095284_n.jpg?sha=c9c8a2f13cf942a8, when it's actually just at www.raheem.ai/media/W1siZiIsIm4xYWVwNHh1aXdlbHBycXNwd3hhLmpwZyJdXQ/17555505_10101361529505761_792095284_n.jpg?sha=c9c8a2f13cf942a8.

**Comment by kidbombay** [comment]
Does it show up correctly on incident show page?

**Comment by jhankin** [comment]
No
