### ISSUE TITLE
Get and Search Incidents should require read_key, not write_key

### ISSUE THREAD

**Issue by jhankin** [Raheem-ai/seed_web#50]
The server gives an error when calling `GET /api/v1/incidents` with no `write_key` parameter, but if we're checking a key at all for those it should be the `read_key`.

**Comment by kidbombay** [comment]
We don't have support for read only/write accepted on the back end yet. Is this needed for hackathon @BrandonAnderson ?

**Comment by jhankin** [comment]
To be clear, I don't think this is a blocker for the hackathon, just wanted
to log it as an issue.

**Comment by kidbombay** [comment]
Related to #55
