### ISSUE TITLE
For hackathon: Raise Incident pagination limit to 100

### ISSUE THREAD

**Issue by jhankin** [Raheem-ai/seed_web#51]
To give us the data we need to build the dashboard (i.e., all incidents that match a query, with accompanying lat/long), we need to be able to retrieve all the matching records in a single call.  Ideally they'd come down in some kind of abridged form and then you'd drill in to get details, but at a bare minimum we need to make pagination optional or remove it entirely.

**Comment by kidbombay** [comment]
Why do we need all matching calls? This would greatly slow down the response time if there were 100+ results.

**Comment by jhankin** [comment]
The primary goal of the hackathon is to get people building the dashboard.  The dashboard requires us to have a set of the incidents that match the search query, such that they can be plotted on the map.

**Comment by kidbombay** [comment]
But that was whole reason to build the report model to give overview. And a client could easily call multiple pages to load or change default page size to be 100. But not having paging is a bad idea.

**Comment by jhankin** [comment]
How can the client change the default page size?  I don't see that documented anywhere.  

Agree that in the long run, not having paging is a bad idea, but for what we're working with today, there aren't all that many records and we can always re-add paging when the data set grows.  I'm fine with setting the default page size to be something large (100 is good, 500 would be better) but whatever the solution is, we have to support the dashboard use case (see https://trello.com/c/QAjqp273/5-design-second-draft) before the hackathon.

**Comment by seansu4you87** [comment]
@kidbombay how can the client set the page size?  If that's the case, we can just have them set large pagination sizes and problem solved right?

**Comment by kidbombay** [comment]
There should still be limit to page size as it could crash the server if
too large a request.
100 max is what most APIs do.

Ketan Anjaria

Developer & Designer <http://kidbombay.com>, Writer
<https://medium.com/@kidbombay>, Photographer
<http://instagram.com/kidbombay>

@kidbombay <http://twitter.com/kidbombay>

415-260-8742

**Comment by seansu4you87** [comment]
@kidbombay i think what Joe is getting at for the scope of this ticket/hackathon, we basically want to remove pagination.  Then as we start getting more incidents, we'll consider problems of scale

**Comment by kidbombay** [comment]
I don't think that's a good idea. I think we should keep scaling in mind. The UI for mapping will be very heavy if we allow more than 100 items. Plus there's nothing to stop front end folks from calling additional data as needed right now anyway.

**Comment by kidbombay** [comment]
And it will create more work for both backend and front end later if we then remove the limit. We have 25 devs coming. Let's do it the right way.

**Comment by jhankin** [comment]
@kidbombay so I thought about this more on the way home and I think you're right -- 100 incidents is probably plenty for a mapping UI, and the dashboard can implement a "Next 100" link of some kind.  I'll change the title of this issue to reflect.

**Comment by kidbombay** [comment]
We just need to add a .per(100) to https://github.com/Raheem-ai/seed_web/blob/master/app/controllers/api/v1/incidents_controller.rb line 11
I would prefer we do it at the controller level and not the model level from Kaminari as the API might have different limits than a web view.
