### ISSUE TITLE
Add column on Incident indicating if data is fake

### ISSUE THREAD

**Issue by jhankin** [Raheem-ai/seed_web#53]
We can use that to distinguish pre-launch test data and dummy generated data from actual production data generated by the chatbot.  See #52 

cc: @kidbombay @samweiller

**Comment by kidbombay** [comment]
WE have a separate task to know which client created the incident for tracking purposes. Right now that would be related to the write key. What if we combined and said there's a "test" client creating these?

**Comment by kidbombay** [comment]
#41

**Comment by jhankin** [comment]
Interesting.  We've also talked about wanting to have some kind of "confidence" field on the Incident (just logged as #54), which could be 0 for stuff we know is fake and non-zero for the rest.

**Comment by kidbombay** [comment]
Is confidence calculated or set once? We could set confidence to -1 to indicate fake data as well but seems like reaching. An Incident could have a confidence of zero based on the data. No way to know yet tho since we don't have a confidence, or we should probably call it percent_complete yet.

**Comment by kidbombay** [comment]
Actually that kind of answers the question. A fake incident could be 100% complete but still fake. So I don't think confidence/percent_complete is the thing we should use. For speed incident.is_fake, default: true migration would be fine but let's also keep in mindthe client question.

**Comment by jhankin** [comment]
Closing and reopening clean ticket.
