### ISSUE TITLE
Add completeness value for Incident

### ISSUE THREAD

**Issue by jhankin** [Raheem-ai/seed_web#54]
Some sort of data science-y modeling indicating how confident we are in an incident's validity as a data point -- especially around completeness of report.  Note that this is NOT meant to be a judgment as to whether or not we think the incident's details are true -- just an index as to how "good" the data is.

**Comment by kidbombay** [comment]
Can we call this percent_complete, I think it's what we agreed to in a meeting previously. Clarifies it's not about good data but completeness of data.

percent_complete:integer, default: 0
And a method or job to determine how to calculate that after commit

**Comment by jhankin** [comment]
Sure -- I thought we'd discussed two separate things, one about completeness and one that was more of a statistical thing.  `percent_complete` is definitely the easier of the two.

**Comment by kidbombay** [comment]
Ah you are saying to have both? Might have forgotten about that. We need some data sciency folks to chime in on this. Good task for Hackathon.

**Comment by jhankin** [comment]
Closing in favor of two new clean issues.
