### ISSUE TITLE
Add positive count and negative count to `meta` dictionary when getting incidents

### ISSUE THREAD

**Issue by jhankin** [Raheem-ai/seed_web#56]
Dashboard designs call for a count of positive incidents and negative incidents when making a query.  We can include that in the `meta` dictionary that comes down in a `GET /incidents` call, where the pagination info lives.

**Comment by kidbombay** [comment]
I would rather create the incident query model as there will be more data than this like population etc and return that model instead with the paged incidents instead.

**Comment by jhankin** [comment]
Let's not overbuild prematurely -- right now what we're giving back in the `GET /incidents` call is exactly what is needed, minus these two values.  As the dashboard designs evolve we can build out a more robust model based on what the actual needs are.

**Comment by kidbombay** [comment]
Doesn't the design have population and city info? There is a lot more on the dashboard page than the plain search API provides. I don't think it's overbuilding to do it that right way. It's not metadata but core to the query. We're not just getting incidents we're asking for get me info on this place and it's incidents.

**Comment by jhankin** [comment]
We already decided to punt on population and city info for now.  `meta` already includes the total number of records for the query, so adding the count of how many are positive and how many are negative seems like a natural tweak without additional overhead.

**Comment by kidbombay** [comment]
Meta is generic. Not specific to any model. I don't think it's good API
design to have meta fields only for a certain model.


Ketan Anjaria

Developer & Designer <http://kidbombay.com>, Writer
<https://medium.com/@kidbombay>, Photographer
<http://instagram.com/kidbombay>

@kidbombay <http://twitter.com/kidbombay>

415-260-8742

**Comment by kidbombay** [comment]
https://projects.invisionapp.com/share/NKAK7ESUV#/screens/220204924 - according to the latest invision there is def additional data. It looks like a report model to me. Not just an incident query.

**Comment by kidbombay** [comment]
https://projects.invisionapp.com/share/NKAK7ESUV#/screens/220204927
Same here

**Comment by kidbombay** [comment]
https://projects.invisionapp.com/share/NKAK7ESUV#/screens/220204932
And the report has data on the query entered. We could let the front track/store this but since we using this data anyway (and it may get transformed from initial query) the backend should return this.

**Comment by kidbombay** [comment]
Closing in favor of #58
