### ISSUE TITLE
No API connection to localhost

### ISSUE THREAD

**Issue by khadijah-coakley** [Raheem-ai/seed_web#80]
Fetch API cannot load http://staging.raheem.ai/api/v1/incidents?filters=&write_key=b1b6100b02ec51abd0e5d94ca73d5340. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

<img width="1914" alt="screenshot 2017-04-11 20 09 56" src="https://cloud.githubusercontent.com/assets/5539112/24937267/15cffbf4-1ef5-11e7-8816-35ce6f7650ac.png">

@jhankin @seansu4you87

**Comment by zaach** [comment]
This was fixed.
