### ISSUE TITLE
No API connection to localhost #80

### ISSUE THREAD

**Issue by BrandonAnderson** [Raheem-ai/seed_web#91]
Fetch API cannot load http://staging.raheem.ai/api/v1/incidents?filters=&write_key=b1b6100b02ec51abd0e5d94ca73d5340. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by khadijah-coakley** [comment]
Why did you close this?

**Comment by jhankin** [comment]
@khadijah-coakley this must have gotten clobbered when pushing out a commit for testing.  Will repush a commit to enable CORS on staging.

**Comment by jhankin** [comment]
@khadijah-coakley just re-pushed the `hackathon` branch to staging.  Is there an easy way to validate that this works?

**Comment by zaach** [comment]
Works 👍🏾
