### ISSUE TITLE
GET /api/v1/incidents returns 500 error

### ISSUE THREAD

**Issue by zaach** [Raheem-ai/seed_web#97]
<img width="669" alt="screen shot 2017-04-12 at 10 06 49 am" src="https://cloud.githubusercontent.com/assets/3903/24970133/079e87f8-1f68-11e7-86f5-3c5e47b0b947.png">

Searching by a rating or incident type ID works fine, but with nothing specified it gives a 500 error.

**Comment by jhankin** [comment]
@zaach bad DB migration, should be resolved now
